#include "Prelude.h"
#include "debug.h"
#include "runtime.h"
#include "PreludeBase.h"
#include "PreludeCompare.h"
#include "PreludeNum.h"
#include "PreludeList.h"
#include "PreludeString.h"
#include "PreludeRead.h"
#include "PreludeMonad.h"
#include "PreludeTuple.h"

